### ISSUE TITLE
should check robots.txt to allow instances to opt out

### ISSUE THREAD

**Issue by tyrm** [g3rv4/FakeRelay#2]

**Comment by g3rv4** [comment]
@tyrm can you expand on this? FakeRelay is not scraping anything :) admins add it as a relay and then use an API key to push content to their instances.

**Comment by tyrm** [comment]
i don't want this software to be able to get posts from my instance. there should be an option to allow an instance to opt out.

**Comment by g3rv4** [comment]
This software is not getting posts from your instance. This software pushes an activitypub message to the server that added it as a relay.

FakeRelay never pulls the data from your site, it's the instance is the one who fetches the data from your site. If you want to avoid the instance from getting your content, you should block that as anyone wanting to index this on their server could do a search of that url and that will get your toot indexed.

robots.txt tells crawlers and bots what to visit (and what not to visit). Since FakeRelay isn't visiting anything, I don't think it makes sense to do a request to each of these sites every time it's about to forward a url.

**Comment by tyrm** [comment]
@g3rv4 is correct, the issue is not FakeRelay, it's the turotials that were released around it, providing code to scrape posts from an instance without asking and feed them into another instance.
